"""
    Assessments Service

    A set of API endpoints that allow you to get score sheet  # noqa: E501

    The version of the OpenAPI document: 1.00
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_assessments_sdk
from osis_assessments_sdk.model.score_responsible_person import ScoreResponsiblePerson
globals()['ScoreResponsiblePerson'] = ScoreResponsiblePerson
from osis_assessments_sdk.model.array_of_score_responsible_person import ArrayOfScoreResponsiblePerson


class TestArrayOfScoreResponsiblePerson(unittest.TestCase):
    """ArrayOfScoreResponsiblePerson unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArrayOfScoreResponsiblePerson(self):
        """Test ArrayOfScoreResponsiblePerson"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ArrayOfScoreResponsiblePerson()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
