"""
    Assessments Service

    A set of API endpoints that allow you to get score sheet and submit attendance mark  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_assessments_sdk
from osis_assessments_sdk.api.attendance_mark_api import AttendanceMarkApi  # noqa: E501


class TestAttendanceMarkApi(unittest.TestCase):
    """AttendanceMarkApi unit test stubs"""

    def setUp(self):
        self.api = AttendanceMarkApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_attendancemarkrequested_list(self):
        """Test case for attendancemarkrequested_list

        """
        pass

    def test_attendancemarkscalendars_list(self):
        """Test case for attendancemarkscalendars_list

        """
        pass

    def test_requestattendancemark(self):
        """Test case for requestattendancemark

        """
        pass


if __name__ == '__main__':
    unittest.main()
