"""
    Assessments Service

    A set of API endpoints that allow you to get score sheet  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_assessments_sdk
from osis_assessments_sdk.model.session_exam import SessionExam


class TestSessionExam(unittest.TestCase):
    """SessionExam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionExam(self):
        """Test SessionExam"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SessionExam()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
