"""
    Assessments Service

    A set of API endpoints that allow you to get score sheet and submit attendance mark  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_assessments_sdk
from osis_assessments_sdk.model.learning_unit_progress import LearningUnitProgress
globals()['LearningUnitProgress'] = LearningUnitProgress
from osis_assessments_sdk.model.progress_overview import ProgressOverview


class TestProgressOverview(unittest.TestCase):
    """ProgressOverview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProgressOverview(self):
        """Test ProgressOverview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProgressOverview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
