"""
    Assessments Service

    A set of API endpoints that allow you to get score sheet and submit attendance mark  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_assessments_sdk
from osis_assessments_sdk.model.attendance_mark_requested import AttendanceMarkRequested


class TestAttendanceMarkRequested(unittest.TestCase):
    """AttendanceMarkRequested unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttendanceMarkRequested(self):
        """Test AttendanceMarkRequested"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttendanceMarkRequested()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
