"""
    Assessments Service

    A set of API endpoints that allow you to get score sheet and submit attendance mark  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_assessments_sdk
from osis_assessments_sdk.model.attendance_mark_calendar import AttendanceMarkCalendar


class TestAttendanceMarkCalendar(unittest.TestCase):
    """AttendanceMarkCalendar unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttendanceMarkCalendar(self):
        """Test AttendanceMarkCalendar"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttendanceMarkCalendar()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
