"""
    Assessments Service

    A set of API endpoints that allow you to get score sheet and submit attendance mark  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_assessments_sdk
from osis_assessments_sdk.model.score_responsible_person import ScoreResponsiblePerson


class TestScoreResponsiblePerson(unittest.TestCase):
    """ScoreResponsiblePerson unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScoreResponsiblePerson(self):
        """Test ScoreResponsiblePerson"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScoreResponsiblePerson()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
