"""
    Assessments Service

    A set of API endpoints that allow you to get score sheet and submit attendance mark  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_assessments_sdk
from osis_assessments_sdk.model.request_attendance_mark_command import RequestAttendanceMarkCommand


class TestRequestAttendanceMarkCommand(unittest.TestCase):
    """RequestAttendanceMarkCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestAttendanceMarkCommand(self):
        """Test RequestAttendanceMarkCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestAttendanceMarkCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
