"""
    Assessments Service

    A set of API endpoints that allow you to get score sheet  # noqa: E501

    The version of the OpenAPI document: 1.00
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_assessments_sdk
from osis_assessments_sdk.model.learning_unit_progress_overview import LearningUnitProgressOverview


class TestLearningUnitProgressOverview(unittest.TestCase):
    """LearningUnitProgressOverview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLearningUnitProgressOverview(self):
        """Test LearningUnitProgressOverview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LearningUnitProgressOverview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
