"""
    Assessments Service

    A set of API endpoints that allow you to get score sheet and submit attendance mark  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_assessments_sdk
from osis_assessments_sdk.api.score_encoding_api import ScoreEncodingApi  # noqa: E501


class TestScoreEncodingApi(unittest.TestCase):
    """ScoreEncodingApi unit test stubs"""

    def setUp(self):
        self.api = ScoreEncodingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_assessment_email(self):
        """Test case for assessment_email

        """
        pass

    def test_get_current_session(self):
        """Test case for get_current_session

        """
        pass

    def test_get_next_session(self):
        """Test case for get_next_session

        """
        pass

    def test_get_overview(self):
        """Test case for get_overview

        """
        pass

    def test_get_previous_session(self):
        """Test case for get_previous_session

        """
        pass

    def test_get_score_responsible_list(self):
        """Test case for get_score_responsible_list

        """
        pass

    def test_score_sheet_xls_export(self):
        """Test case for score_sheet_xls_export

        """
        pass


if __name__ == '__main__':
    unittest.main()
