# flake8: noqa

"""
    Assessments Service

    A set of API endpoints that allow you to get score sheet  # noqa: E501

    The version of the OpenAPI document: 1.00
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from osis_assessments_sdk.api_client import ApiClient

# import Configuration
from osis_assessments_sdk.configuration import Configuration

# import exceptions
from osis_assessments_sdk.exceptions import OpenApiException
from osis_assessments_sdk.exceptions import ApiAttributeError
from osis_assessments_sdk.exceptions import ApiTypeError
from osis_assessments_sdk.exceptions import ApiValueError
from osis_assessments_sdk.exceptions import ApiKeyError
from osis_assessments_sdk.exceptions import ApiException
